#!/usr/bin/env bash
# Generate asterism.env with strong random secrets for a production deploy.
#
# One command instead of hand-editing asterism.env.example — so an operator can
# never accidentally ship a weak/blank secret. Run it ON the deploy host (it prints
# the login password to YOUR terminal so you can save it; it is not stored in clear
# anywhere else, and is never committed).
#
# Usage:
#   ./scripts/init-secrets.sh [DOMAIN]
#     DOMAIN   host clients use — the server's IP (self-signed cert) or a FQDN
#              (real cert; also set ASTERISM_TLS_EMAIL=you@example.com). Prompted
#              if omitted on an interactive terminal.
#
# Optional env overrides:
#   ASTERISM_TLS_EMAIL          default "internal" (self-signed). An email -> ACME.
#   ASTERISM_GATE_PASSWORD      default: auto-generated.
#   ASTERISM_DEMO_CORS_ORIGINS  default: empty.
#   FORCE=1                     overwrite an existing asterism.env. NOTE: rotating
#                               GATE_SECRET logs everyone out; rotating API_TOKEN
#                               means re-entering it in the UI.
#
# Writes ./asterism.env (chmod 600). Then: docker compose -f compose.prod.yaml up -d --build
set -euo pipefail

cd "$(dirname "$0")/.."   # repo root
ENV_FILE="asterism.env"

command -v openssl >/dev/null 2>&1 || { echo "error: openssl is required" >&2; exit 1; }

if [[ -f "$ENV_FILE" && "${FORCE:-}" != "1" ]]; then
  echo "error: $ENV_FILE already exists — refusing to overwrite." >&2
  echo "       (set FORCE=1 to rotate all secrets; this logs everyone out.)" >&2
  exit 1
fi

# --- host / domain ----------------------------------------------------------
DOMAIN="${1:-${ASTERISM_DOMAIN:-}}"
if [[ -z "$DOMAIN" ]]; then
  default_ip="$(hostname -I 2>/dev/null | awk '{print $1}')"
  if [[ -t 0 ]]; then
    read -r -p "Domain or server IP clients will use [${default_ip:-required}]: " DOMAIN
    DOMAIN="${DOMAIN:-$default_ip}"
  fi
fi
if [[ -z "$DOMAIN" ]]; then
  echo "error: no domain/IP. Pass it as an argument or set ASTERISM_DOMAIN." >&2
  exit 1
fi

TLS_EMAIL="${ASTERISM_TLS_EMAIL:-internal}"
CORS="${ASTERISM_DEMO_CORS_ORIGINS:-}"

# --- secrets (hex => no '$', so no Compose env_file-interpolation escaping) --
API_TOKEN="$(openssl rand -hex 32)"
GATE_SECRET="$(openssl rand -hex 32)"
if [[ -n "${ASTERISM_GATE_PASSWORD:-}" ]]; then
  GATE_PASSWORD="$ASTERISM_GATE_PASSWORD"; PW_NOTE=""
else
  GATE_PASSWORD="$(openssl rand -hex 16)"; PW_NOTE=" (auto-generated)"
fi

umask 077
cat > "$ENV_FILE" <<EOF
# Generated by scripts/init-secrets.sh — do NOT commit. Values are hex (no '\$').
ASTERISM_DOMAIN=$DOMAIN
ASTERISM_TLS_EMAIL=$TLS_EMAIL
ASTERISM_API_TOKEN=$API_TOKEN
ASTERISM_GATE_PASSWORD=$GATE_PASSWORD
ASTERISM_GATE_SECRET=$GATE_SECRET
ASTERISM_DEMO_CORS_ORIGINS=$CORS
EOF
chmod 600 "$ENV_FILE"

cat <<EOF

Wrote $ENV_FILE (chmod 600) for host: $DOMAIN

  Login password${PW_NOTE}: $GATE_PASSWORD
  API token (paste into the UI settings for write/design): $API_TOKEN

>> SAVE these now (e.g. a password manager) — they are not shown again. <<

Launch:  docker compose -f compose.prod.yaml up -d --build
EOF
